# Generated by Django 5.2.1 on 2025-06-03 15:43

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('category', models.CharField(choices=[('salary', 'Зарплата'), ('materials', 'Учебные материалы'), ('events', 'Мероприятия'), ('utilities', 'Коммунальные услуги')], max_length=20)),
                ('supplier', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('payment_method', models.CharField(choices=[('cash', 'Наличные'), ('card', 'Безналичный'), ('online', 'Онлайн платеж')], max_length=10)),
                ('invoice', models.FileField(blank=True, null=True, upload_to='expenses/invoices/')),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Создание'), ('update', 'Обновление'), ('delete', 'Удаление')], max_length=10)),
                ('model_name', models.CharField(max_length=50)),
                ('object_id', models.IntegerField()),
                ('details', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11')])),
                ('parallel', models.CharField(choices=[('А', 'А'), ('Б', 'Б'), ('В', 'В'), ('Г', 'Г')], max_length=1)),
                ('max_students', models.IntegerField(default=25)),
            ],
            options={
                'unique_together': {('number', 'parallel')},
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('birth_date', models.DateField()),
                ('parent_contacts', models.TextField()),
                ('admission_date', models.DateField()),
                ('status', models.CharField(choices=[('studying', 'Обучается'), ('reserve', 'Резерв'), ('expelled', 'Отчислен')], default='studying', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.grade')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=9)),
                ('status', models.CharField(choices=[('confirmed', 'Подтверждена'), ('pending', 'Ожидает оплаты'), ('cancelled', 'Отменена')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('intended_grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.grade')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.student')),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('payment_method', models.CharField(choices=[('cash', 'Наличные'), ('card', 'Безналичный'), ('online', 'Онлайн платеж')], max_length=10)),
                ('income_type', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('paid', 'Оплачено'), ('partial', 'Частично'), ('refund', 'Возврат')], default='paid', max_length=10)),
                ('transaction_id', models.CharField(max_length=50, unique=True)),
                ('notes', models.TextField(blank=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.student')),
            ],
        ),
    ]
