# Generated by Django 5.2.1 on 2025-06-04 08:32

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Журнал аудита', 'verbose_name_plural': 'Журналы аудита'},
        ),
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-date'], 'verbose_name': 'Расход', 'verbose_name_plural': 'Расходы'},
        ),
        migrations.AlterModelOptions(
            name='grade',
            options={'verbose_name': 'Класс', 'verbose_name_plural': 'Классы'},
        ),
        migrations.AlterModelOptions(
            name='income',
            options={'ordering': ['-date'], 'verbose_name': 'Приход', 'verbose_name_plural': 'Приходы'},
        ),
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-created_at'], 'verbose_name': 'Бронирование', 'verbose_name_plural': 'Бронирования'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['grade', 'full_name'], 'verbose_name': 'Ученик', 'verbose_name_plural': 'Ученики'},
        ),
        migrations.AddField(
            model_name='student',
            name='number_contract',
            field=models.IntegerField(blank=True, null=True, verbose_name='Номер контракта'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Создание'), ('update', 'Обновление'), ('delete', 'Удаление')], max_length=10, verbose_name='Действие'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='details',
            field=models.TextField(blank=True, verbose_name='Детали'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='model_name',
            field=models.CharField(max_length=50, verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='object_id',
            field=models.IntegerField(verbose_name='ID объекта'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Временная метка'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('salary', 'Зарплата'), ('materials', 'Учебные материалы'), ('events', 'Мероприятия'), ('utilities', 'Коммунальные услуги')], max_length=20, verbose_name='Категория расхода'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(verbose_name='Дата расхода'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='invoice',
            field=models.FileField(blank=True, null=True, upload_to='expenses/invoices/', verbose_name='Счет/фактура'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Наличные'), ('card', 'Безналичный'), ('online', 'Онлайн платеж')], max_length=10, verbose_name='Способ оплаты'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='supplier',
            field=models.CharField(max_length=200, verbose_name='Поставщик/контрагент'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='max_students',
            field=models.IntegerField(default=25, verbose_name='Максимальное количество учеников'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='number',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11')], verbose_name='Номер класса'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='parallel',
            field=models.CharField(choices=[('А', 'А'), ('Б', 'Б'), ('В', 'В'), ('Г', 'Г')], max_length=1, verbose_name='Параллель'),
        ),
        migrations.AlterField(
            model_name='income',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='income',
            name='date',
            field=models.DateField(verbose_name='Дата платежа'),
        ),
        migrations.AlterField(
            model_name='income',
            name='income_type',
            field=models.CharField(max_length=100, verbose_name='Статья дохода'),
        ),
        migrations.AlterField(
            model_name='income',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Примечания'),
        ),
        migrations.AlterField(
            model_name='income',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Наличные'), ('card', 'Безналичный'), ('online', 'Онлайн платеж')], max_length=10, verbose_name='Способ оплаты'),
        ),
        migrations.AlterField(
            model_name='income',
            name='status',
            field=models.CharField(choices=[('paid', 'Оплачено'), ('partial', 'Частично'), ('refund', 'Возврат')], default='paid', max_length=10, verbose_name='Статус оплаты'),
        ),
        migrations.AlterField(
            model_name='income',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.student', verbose_name='Ученик'),
        ),
        migrations.AlterField(
            model_name='income',
            name='transaction_id',
            field=models.CharField(max_length=50, unique=True, verbose_name='Номер транзакции'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='academic_year',
            field=models.CharField(max_length=9, verbose_name='Учебный год'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='intended_grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.grade', verbose_name='Предполагаемый класс'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Подтверждена'), ('pending', 'Ожидает оплаты'), ('cancelled', 'Отменена')], max_length=10, verbose_name='Статус брони'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.student', verbose_name='Ученик'),
        ),
        migrations.AlterField(
            model_name='student',
            name='admission_date',
            field=models.DateField(verbose_name='Дата поступления'),
        ),
        migrations.AlterField(
            model_name='student',
            name='birth_date',
            field=models.DateField(verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='student',
            name='full_name',
            field=models.CharField(max_length=200, verbose_name='ФИО ученика'),
        ),
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.grade', verbose_name='Класс'),
        ),
        migrations.AlterField(
            model_name='student',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активный'),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent_contacts',
            field=models.TextField(verbose_name='Контакты родителей'),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('studying', 'Обучается'), ('reserve', 'Резерв'), ('expelled', 'Отчислен')], default='studying', max_length=10, verbose_name='Статус'),
        ),
    ]
