# Generated by Django 5.2.1 on 2025-06-14 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_auditlog_options_alter_expense_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='pol',
            field=models.CharField(blank=True, choices=[('male', 'муж'), ('famale', 'жен')], default='male', max_length=10, null=True, verbose_name='Пол'),
        ),
    ]
