# Generated by Django 5.2.1 on 2025-06-14 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_student_pol'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='receipt_pdf',
            field=models.FileField(blank=True, null=True, upload_to='receipts/', verbose_name='Квитанция PDF'),
        ),
    ]
