# Generated by Django 5.2.1 on 2025-06-16 07:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_income_receipt_pdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=9, verbose_name='Учебный год (например: 2024-2025)')),
                ('start_date', models.DateField(verbose_name='Дата начала учебного года')),
                ('end_date', models.DateField(verbose_name='Дата окончания учебного года')),
                ('is_current', models.BooleanField(default=False, verbose_name='Текущий учебный год')),
            ],
            options={
                'verbose_name': 'Учебный год',
                'verbose_name_plural': 'Учебные годы',
            },
        ),
        migrations.AddField(
            model_name='student',
            name='contract_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Сумма контракта (сом)'),
        ),
        migrations.AddField(
            model_name='student',
            name='contract_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата контракта'),
        ),
        migrations.AddField(
            model_name='student',
            name='contract_file',
            field=models.FileField(blank=True, null=True, upload_to='contracts/', verbose_name='Файл контракта'),
        ),
        migrations.AddField(
            model_name='student',
            name='current_year_paid',
            field=models.BooleanField(default=False, verbose_name='Оплачен текущий учебный год'),
        ),
        migrations.AddField(
            model_name='student',
            name='payment_notes',
            field=models.TextField(blank=True, verbose_name='Примечания по оплате'),
        ),
        migrations.AlterField(
            model_name='income',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата платежа'),
        ),
        migrations.AlterField(
            model_name='income',
            name='income_type',
            field=models.CharField(default='Оплата обучения', max_length=100, verbose_name='Статья дохода'),
        ),
        migrations.AlterField(
            model_name='student',
            name='number_contract',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер контракта'),
        ),
        migrations.AlterField(
            model_name='student',
            name='pol',
            field=models.CharField(blank=True, choices=[('male', 'муж'), ('female', 'жен')], default='male', max_length=10, null=True, verbose_name='Пол'),
        ),
        migrations.AddField(
            model_name='income',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.academicyear', verbose_name='Учебный год'),
        ),
    ]
