# Generated by Django 5.2.1 on 2025-06-16 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_academicyear_student_contract_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='is_full_year_payment',
            field=models.BooleanField(default=False, verbose_name='Оплата за весь учебный год'),
        ),
        migrations.AddField(
            model_name='income',
            name='paid_months',
            field=models.JSONField(blank=True, default=list, verbose_name='Оплаченные месяцы (номера)'),
        ),
    ]
