# Generated by Django 5.2.1 on 2025-06-20 11:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_income_is_full_year_payment_income_paid_months'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expense',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Кто создал'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expense',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер счета'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('salary', 'Зарплата'), ('materials', 'Учебные материалы'), ('events', 'Мероприятия'), ('utilities', 'Коммунальные услуги'), ('other', 'Другие расходы')], max_length=20, verbose_name='Категория расхода'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Наличные'), ('card', 'Безналичный'), ('bank_transfer', 'Банковский перевод'), ('online', 'Онлайн платеж')], max_length=15, verbose_name='Способ оплаты'),
        ),
    ]
