# Generated by Django 5.2.1 on 2025-06-26 10:13

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_expense_created_at_expense_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название должности')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
            },
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('salary', 'Зарплата'), ('materials', 'Учебные материалы'), ('events', 'Мероприятия'), ('utilities', 'Коммунальные услуги'), ('other', 'Другие расходы'), ('arenda', 'Аренда')], max_length=20, verbose_name='Категория расхода'),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО сотрудника')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('gender', models.CharField(choices=[('male', 'Мужской'), ('female', 'Женский')], max_length=10, verbose_name='Пол')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('contract_type', models.CharField(choices=[('permanent', 'Бессрочный'), ('fixed_term', 'Срочный'), ('temporary', 'Временный')], max_length=20, verbose_name='Тип контракта')),
                ('contract_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер контракта')),
                ('contract_start_date', models.DateField(verbose_name='Дата начала контракта')),
                ('contract_end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания контракта')),
                ('monthly_salary', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Месячная зарплата (сом)')),
                ('contract_file', models.FileField(blank=True, null=True, upload_to='employee_contracts/', verbose_name='Файл контракта')),
                ('hire_date', models.DateField(verbose_name='Дата приема на работу')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный сотрудник')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.position', verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='SalaryPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Сумма выплаты')),
                ('payment_date', models.DateField(verbose_name='Дата выплаты')),
                ('for_month', models.DateField(verbose_name='За месяц')),
                ('payment_method', models.CharField(choices=[('cash', 'Наличные'), ('card', 'Безналичный'), ('bank_transfer', 'Банковский перевод'), ('online', 'Онлайн платеж')], max_length=15, verbose_name='Способ оплаты')),
                ('is_bonus', models.BooleanField(default=False, verbose_name='Премиальная выплата')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Кто создал')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Зарплатная выплата',
                'verbose_name_plural': 'Зарплатные выплаты',
                'ordering': ['-payment_date'],
            },
        ),
    ]
