# Generated by Django 5.2.1 on 2025-07-17 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_application_alter_expense_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('subject', models.CharField(max_length=100, verbose_name='Предмет')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='teachers/', verbose_name='Фото')),
                ('is_main', models.BooleanField(default=False, verbose_name='Главный учитель?')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
            ],
            options={
                'verbose_name': 'Учитель',
                'verbose_name_plural': 'Учителя',
                'ordering': ['order', 'last_name'],
            },
        ),
    ]
