# Generated by Django 5.2.1 on 2025-07-17 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('level', models.CharField(max_length=20, verbose_name='Класс')),
                ('achievements', models.TextField(verbose_name='Достижения')),
                ('image', models.ImageField(upload_to='students/', verbose_name='Фото')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Показывать на главной?')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
            ],
            options={
                'verbose_name': 'Ученик',
                'verbose_name_plural': 'Ученики',
                'ordering': ['order', 'last_name'],
            },
        ),
    ]
