# Generated by Django 5.2.1 on 2025-08-03 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_galleryevent_galleryimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='is_publish',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='На лицевую часть публиковать?'),
        ),
    ]
