# Generated by Django 5.2.1 on 2025-08-07 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_teacher_is_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Номер квитанции'),
        ),
    ]
