# Generated by Django 5.2.1 on 2025-08-08 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_expense_receipt_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Graduate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='Введите полное имя выпускника (Иванов Иван Иванович)', max_length=100, verbose_name='ФИО выпускника')),
                ('graduation_year', models.PositiveIntegerField(help_text='Например: 2020', verbose_name='Год выпуска')),
                ('achievements', models.TextField(blank=True, help_text='Кратко опишите достижения выпускника (место работы, учебы, награды)', verbose_name='Достижения после школы')),
                ('image', models.ImageField(blank=True, help_text='Загрузите фотографию выпускника', upload_to='graduates/', verbose_name='Фотография')),
                ('order', models.PositiveIntegerField(default=0, help_text='Чем больше число, тем выше в списке', verbose_name='Порядок сортировки')),
            ],
            options={
                'verbose_name': 'Выпускник',
                'verbose_name_plural': 'Выпускники',
                'ordering': ['-order', '-graduation_year', 'username'],
            },
        ),
    ]
