# Generated by Django 5.2.1 on 2025-08-08 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_graduate'),
    ]

    operations = [
        migrations.AddField(
            model_name='graduate',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
