# Generated by Django 5.2.1 on 2026-05-24 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_graduate_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='enrollment_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrolled_students', to='core.academicyear', verbose_name='Год зачисления (с какого года учится)'),
        ),
        migrations.AddField(
            model_name='student',
            name='is_graduated',
            field=models.BooleanField(default=False, verbose_name='Выпустился'),
        ),
    ]
