# Generated by Django 5.2.1 on 2026-06-01 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentYearContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма контракта (сом)')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.academicyear', verbose_name='Учебный год')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='year_contracts', to='core.student', verbose_name='Ученик')),
            ],
            options={
                'verbose_name': 'Контракт по году',
                'verbose_name_plural': 'Контракты по годам',
                'unique_together': {('student', 'academic_year')},
            },
        ),
    ]
