# Generated by Django 5.2.1 on 2026-07-08 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_grade_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.academicyear', verbose_name='Учебный год'),
        ),
    ]
