# Generated by Django 5.2.1 on 2026-08-18 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_backfill_expense_academic_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarypayment',
            name='expense',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_payment', to='core.expense', verbose_name='Связанный расход'),
        ),
    ]
